image: atlassian/default-image:2

pipelines:
    branches:
      main:
        - step:
           script:
             - add-apt-repository universe
             - apt-get update -y
             - apt-get install python3-pip python3-notebook jupyter jupyter-core python-ipykernel
             - which jupyter
             - jupyter nbconvert --to script ipynb/*.ipynb
             - ls
             - git remote add sync git@github.com:miyabilink/sukkiri-spython-codes.git
             - git checkout main
             - git pull
             - python py2ipynb.py
             - git merge origin/main
             - git filter-branch -f --env-filter "GIT_AUTHOR_NAME='Shinpei KUDO'; GIT_AUTHOR_EMAIL='kudo@miyabilink.jp'; GIT_COMMITTER_NAME='Shinpei KUDO'; GIT_COMMITTER_EMAIL='kudo@miyabilink.jp';" --tag-name-filter cat -- --all
             - git push sync --tags
             - git push -f sync main
